better menu system

diff --git a/vump b/vump
--- a/vump
+++ b/vump
@@ -20,6 +20,31 @@ if [[ "${DEBUG-0}" == "1" ]]; then set -o xtrace; fi          # DEBUG=1 will sho
 # │                        VARIABLES                         │
 # ╰──────────────────────────────────────────────────────────╯
 DB_USERNAME="root"
+CONFIRM=""
+
+# Deine all spinnaker icons / colours
+function stylesheet()
+{
+    TEXT_STONE_600='\e[38;2;87;83;78m'
+    TEXT_AMBER_300='\e[38;2;252;211;77m'
+    TEXT_GRAY_500='\e[38;2;107;114;128m'
+    TEXT_RED_600='\e[38;2;220;38;38m'
+    TEXT_SKY_600='\e[38;2;2;132;199m'
+    TEXT_EMERALD_500='\e[38;2;16;185;129m'
+    RESET_TEXT='\e[39m'
+
+    ICON_ROCKET=🚀
+    ICON_HOUSE=🏠
+    ICON_FADE_200=░
+    ICON_CMD=⌘
+    ICON_ARROW_N=↑
+    ICON_ARROW_S=↓
+    ICON_CIRCLE=●
+
+    BORDER_SKY_400='\e[38;2;56;189;248m'
+    BORDER_EMERALD_400='\e[38;2;52;211;153m'
+    BORDER_PINK_400='\e[38;2;244;114;182m'
+}
 
 # ╭──────────────────────────────────────────────────────────╮
 # │                      Trap Functions                      │
@@ -33,13 +58,24 @@ trap "rm -f ./backup.sql" EXIT
 # ╰──────────────────────────────────────────────────────────╯
 function menu_main()
 {
-    printf "Vump Tool\n\n"
-    printf "1. Export Volume contents to host tar.gz file\n"
-    printf "2. Import tar.gz file into a Volume\n"
-    printf "3. Save Volume data to a backup docker image\n"
-    printf "4. Load backup docker image into a Volume\n"
-    printf "5. Save MySQL Volume DB to a backup docker image\n"
-    printf "6. Load backup MySQL DB docker image into DB Volume\n"
+    printf "${TEXT_AMBER_300}Vump Tool${RESET_TEXT}\n\n"
+    printf "1. %-10s  %-20s →\t %-20s\n"  "[Export]"    "🗄  Volume"        "🗜  tar.gz"
+    printf "    ${TEXT_STONE_600}Export contents of a docker volume into a tar.gz file in current directory on host.${RESET_TEXT}\n\n"
+
+    printf "2. %-10s  %-20s →\t %-20s\n" "[Import]"     "🗜  tar.gz"        "🗄  Volume"
+    printf "    ${TEXT_STONE_600}Import contents of a tar.gz file into a specific docker volume.${RESET_TEXT}\n\n"
+
+    printf "3. %-10s  %-20s →\t %-20s\n" "[Save]"       "🗄  Volume"        "🏞  backup image"
+    printf "    ${TEXT_STONE_600}Save contents of a docker volume into a docker container image ready to push to registry.${RESET_TEXT}\n\n"
+
+    printf "4. %-10s  %-20s →\t %-20s\n" "[Load]"       "🏞  backup image"  "🗄  Volume"
+    printf "    ${TEXT_STONE_600}Load contents of backup docker image into a specific docker volume.${RESET_TEXT}\n\n"
+
+    printf "5. %-10s  %-20s →\t %-20s\n" "[DBSave]"     "🛢  MySQL Volume"  "🏞  backup image"
+    printf "    ${TEXT_STONE_600}Save contents of a MySQL database dump on a container to a backup container image ready to push to a registry.${RESET_TEXT}\n\n"
+
+    printf "6. %-10s  %-20s →\t %-20s\n" "[DBLoad]"     "🏞  backup image"  "🛢  MySQL Volume"
+    printf "    ${TEXT_STONE_600}Load contents of a database backup image into a docker container MySQL database.${RESET_TEXT}\n\n"
 
     printf "\n"
     read -n 1 -p "Enter option (1-6) to continue" SELECTION; clear
@@ -71,7 +107,7 @@ function menu_main()
 
 
         *)
-            echo "Unknown option $1"
+            printf "${TEXT_RED_600}Unknown option $1${RESET_TEXT}\n"
             menu_main
             ;;
 
@@ -86,7 +122,7 @@ function menu_main()
 function select_container()
 {
     clear
-    printf "### %s\n\n" "$1"
+    printf "${TEXT_SKY_600}### %s${RESET_TEXT}\n\n" "$1"
 
     printf "Select a Container\n"
 
@@ -103,7 +139,7 @@ function select_container()
     CONTAINER_LINE=$(sed -n ${ANSWER}p <<< "$LIST_OF_CONTAINERS")
     CONTAINER=$(echo $CONTAINER_LINE  | head -n1 | cut -d " " -f2 | xargs )
 
-    echo $CONTAINER
+    # echo $CONTAINER
 }
 
 # ╭──────────────────────────────────────────────────────────╮
@@ -112,7 +148,7 @@ function select_container()
 function select_volume()
 {
     clear
-    printf "### %s\n\n" "$1"
+    printf "${TEXT_SKY_600}### %s${RESET_TEXT}\n\n" "$1"
 
     printf "Select a Volume\n"
 
@@ -129,7 +165,7 @@ function select_volume()
     VOLUME_LINE=$(sed -n ${ANSWER}p <<< "$LIST_OF_VOLUMES")
     VOLUME=$(echo $VOLUME_LINE  | head -n1 | cut -d " " -f1 )
 
-    echo $VOLUME
+    # echo $VOLUME
 }
 
 
@@ -139,7 +175,7 @@ function select_volume()
 function select_image()
 {
     clear
-    printf "### %s\n\n" "$1"
+    printf "${TEXT_SKY_600}### %s${RESET_TEXT}\n\n" "$1"
 
     printf "Select an Image\n"
 
@@ -156,7 +192,7 @@ function select_image()
     IMAGE_LINE=$(sed -n ${ANSWER}p <<< "$LIST_OF_IMAGES")
     IMAGE=$(echo $IMAGE_LINE  | head -n1 | cut -d " " -f1 )
 
-    echo $IMAGE
+    # echo $IMAGE
 
 }
 
@@ -167,16 +203,62 @@ function select_image()
 function ask_question()
 {
     clear
-    printf "### \n\n "
-
     QUESTION=$1
 
-    read -p "$QUESTION" ANSWER
+    printf "${TEXT_SKY_600}### %s${RESET_TEXT}\n\n " "$QUESTION"
 
-    echo $ANSWER
+    read -p ">" ANSWER
+
+    # echo $ANSWER
 }
 
 
+
+# ╭──────────────────────────────────────────────────────────╮
+# │                  Check Y/n to continue                   │
+# ╰──────────────────────────────────────────────────────────╯
+function confirmation()
+{
+    QUESTION=$1
+    printf "${TEXT_AMBER_300}%s${RESET_TEXT}\n" "$QUESTION"
+    read -r -p "Are you sure? [y/N] " response
+    case "$response" in
+        [yY][eE][sS]|[yY]) 
+            CONFIRM="YES"
+            ;;
+        *)
+            CONFIRM=""
+            exit
+            ;;
+    esac
+}
+
+# ╭──────────────────────────────────────────────────────────╮
+# │       Push the new image to the container registry       │
+# ╰──────────────────────────────────────────────────────────╯
+function push_to_registry()
+{
+    clear
+    confirmation "Do you want to push container image to registry?"
+
+    ask_question "specify tag to add to image. [default:latest]"
+    if [ ! -z "${ANSWER}" ]; then
+        TAG="$ANSWER"
+    else
+        TAG="latest"
+    fi
+
+
+    if ! docker image tag > /dev/null 2>&1;
+    then
+        echo "Error: Failed to start busybox backup container"
+        exit 1
+    fi
+
+    ask_question "specify the repository name in the registry."
+    REPOSITORY="$ANSWER"
+
+}
 
 # ╭──────────────────────────────────────────────────────────╮
 # │                          EXPORT                          │
@@ -225,11 +307,7 @@ function cmd_export() {
         exit 1
     fi
 
-    # TODO: check if file exists on host, if it does
-    # create a option for overwrite and check if that's set
-    # TODO: if FILE_NAME starts with / we need to error out
-    # unless we can translate full file paths
-
+    confirmation "You are going to export volume '${VOLUME_NAME}' to a file ${FILE_NAME}"
 
     if ! docker run --rm \
         -v "$VOLUME_NAME":/vackup-volume \
@@ -241,7 +319,7 @@ function cmd_export() {
         exit 1
     fi
 
-    echo "Successfully tar'ed volume $VOLUME_NAME into file $FILE_NAME"
+    printf "${TEXT_EMERALD_500}Successfully tar'ed volume $VOLUME_NAME into file $FILE_NAME ${RESET_TEXT}\n"
 }
 
 
@@ -289,12 +367,9 @@ function cmd_import() {
     then
         echo "Error: Volume $VOLUME_NAME does not exist"
         docker volume create "$VOLUME_NAME"
-    fi
+    fi  
 
-    # TODO: check if file exists on host, if it does
-    # create a option for overwrite and check if that's set
-    # TODO: if FILE_NAME starts with / we need to error out
-    # unless we can translate full file paths    
+    confirmation "You are about to import the data in the file ${FILE_NAME} into the volume '${VOLUME_NAME}'"
 
     if ! docker run --rm \
         -v "$VOLUME_NAME":/vackup-volume \
@@ -306,7 +381,7 @@ function cmd_import() {
         exit 1
     fi
 
-    echo "Successfully unpacked $FILE_NAME into volume $VOLUME_NAME"
+    printf "${TEXT_EMERALD_500}Successfully unpacked $FILE_NAME into volume $VOLUME_NAME ${RESET_TEXT}\n"
 }
 
 
@@ -349,7 +424,6 @@ function cmd_save() {
     # Check parameters are set
     if [ -z "$VOLUME_NAME" ] || [ -z "$IMAGE_NAME" ]; then
         echo "Error: Not enough arguments"
-        usage
         exit 1
     fi
 
@@ -359,6 +433,8 @@ function cmd_save() {
         echo "Error: Volume $VOLUME_NAME does not exist"
         exit 1
     fi
+
+    confirmation "You are about to save the data in the volume '${VOLUME_NAME}' into a container image called '${IMAGE_NAME}' "
 
     # Copy everything from volume to busybox container
     if ! docker run \
@@ -379,7 +455,9 @@ function cmd_save() {
     # Delete the container
     docker container rm "$CONTAINER_ID"
 
-    echo "Successfully copied volume $VOLUME_NAME into image $IMAGE_NAME, under /volume-data"
+    printf "${TEXT_EMERALD_500}Successfully copied volume $VOLUME_NAME into image $IMAGE_NAME, under /volume-data ${RESET_TEXT}\n"
+
+    # push_to_registry
 }
 
 
@@ -432,6 +510,8 @@ cmd_load() {
         docker volume create "$VOLUME_NAME"
     fi
     
+    confirmation "You are about to load the contents of the container image called '${IMAGE_NAME}' into the volume '${VOLUME_NAME}'"
+
     # Copy everything from container into volume under /mount-volume
     if ! docker run --rm \
         -v "$VOLUME_NAME":/mount-volume \
@@ -442,7 +522,7 @@ cmd_load() {
         exit 1
     fi
 
-    echo "Successfully copied /volume-data from $IMAGE_NAME into volume $VOLUME_NAME"
+    printf "${TEXT_EMERALD_500}Successfully copied /volume-data from $IMAGE_NAME into volume $VOLUME_NAME ${RESET_TEXT}\n"
 }
 
 
@@ -529,6 +609,8 @@ function cmd_dbsave() {
         exit 1
     fi
 
+    confirmation "You are about to extract a mysqldump file from the container '${CONTAINER}' into a container image called '${IMAGE_NAME}' "
+
     # Dump Database to /tmp
     if ! docker exec $CONTAINER \
         /bin/sh -c "mysqldump -u$DB_USERNAME -p$DB_PASSWORD -v --single-transaction $DB_DATABASE > /tmp/backup.sql";
@@ -563,7 +645,7 @@ function cmd_dbsave() {
     # Delete the container
     docker container rm "$CONTAINER_ID"
 
-    echo "Successfully copied DB in container $CONTAINER into image $IMAGE_NAME, under /db-data"
+    printf "${TEXT_EMERALD_500}Successfully copied DB in container $CONTAINER into image $IMAGE_NAME, under /db-data${RESET_TEXT}\n"
 }
 
 
@@ -633,6 +715,7 @@ cmd_dbload() {
         exit 1
     fi
 
+    confirmation "You are about to load the mysqldump file on the container image '${IMAGE_NAME}' into the database in the container '${CONTAINER}'"
 
     # Extract backup file out of image
     if ! docker run -v $PWD:/opt/mount --rm --entrypoint cp $IMAGE_NAME /db-data/backup.sql /opt/mount/backup.sql; 
@@ -657,7 +740,7 @@ cmd_dbload() {
         exit 1
     fi
 
-    echo "Successfully loaded the SQL file from the $IMAGE_NAME image, into the $TARGET_CONTAINER DB container."
+    printf "${TEXT_EMERALD_500}Successfully loaded the SQL file from the $IMAGE_NAME image, into the $TARGET_CONTAINER DB container.${RESET_TEXT}\n"
 }
 
 
@@ -667,5 +750,5 @@ function mainmenu()
     menu_main 
 }
 
-
+stylesheet
 mainmenu "$@"
